# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# upper body
Exercise.create(name: "push ups", description: "")
Exercise.create(name: "arm raises", description: "")
Exercise.create(name: "tricep dips", description: "")
Exercise.create(name: "walk-outs", description: "")
Exercise.create(name: "clap push-ups", description: "")
Exercise.create(name: "walking plank", description: "Move from a shoulder plank to a forearm plank by adjusting one arm at a time.")
Exercise.create(name: "burpees", description: "")
Exercise.create(name: "pike push-ups", description: "")
Exercise.create(name: "plank shoulder taps", description: "In a tall plank position lift one hand to touch the opposite shoulder.")
Exercise.create(name: "bird dogs", description: "From a tabletop position extedn one arm and the opposite leg up. Switch sides.")
Exercise.create(name: "reclined rhomboid squeezes", description: "Like stationary rowing. Sit on your tailbone so that your body is in a v shape. Extend your arms and pull them back bringing your shoulderblades together.")

#  lower body
Exercise.create(name: "leg raises", description: "")
Exercise.create(name: "calf raises", description: "")
Exercise.create(name: "jump squats", description: "")
Exercise.create(name: "forward lunges", description: "")
Exercise.create(name: "backward lunges", description: "")
Exercise.create(name: "side lunges", description: "")
Exercise.create(name: "squats", description: "")
Exercise.create(name: "pelvic raises", description: "")
Exercise.create(name: "hydrant leg lift", description: "")

# core and lower body
Exercise.create(name: "side leg lift", description: "Lay on your side, and lift your free leg up towards the sky.")
Exercise.create(name: "scissor kicks", description: "Lay on your back, hover your legs and kick up and down like you're swimming.")
Exercise.create(name: "slicing scissor kicks", description: "Lay on your back, extend your legs up so that your body makes a 90 degree angle. Open your legs into a v shape, and close.")

# core
Exercise.create(name: "v-sits", description: "")
Exercise.create(name: "situps", description: "")
Exercise.create(name: "superman", description: "")
Exercise.create(name: "crunches", description: "")
Exercise.create(name: "mountain climbers", description: "")
Exercise.create(name: "side crunches", description: "")
Exercise.create(name: "bicycles", description: "")
Exercise.create(name: "side plank", description: "")
Exercise.create(name: "plank", description: "")
Exercise.create(name: "scullers", description: "")
Exercise.create(name: "russian twists", description: "")
Exercise.create(name: "burpees", description: "")

# added
Exercise.create(name: "arm circles", description: "")


Tag.create(body_part: "upper_body", exercise_id: 1)
Tag.create(body_part: "upper_body", exercise_id: 2)
Tag.create(body_part: "upper_body", exercise_id: 3)
Tag.create(body_part: "upper_body", exercise_id: 4)
Tag.create(body_part: "upper_body", exercise_id: 5)
Tag.create(body_part: "upper_body", exercise_id: 6)
Tag.create(body_part: "upper_body", exercise_id: 7)
Tag.create(body_part: "upper_body", exercise_id: 8)
Tag.create(body_part: "upper_body", exercise_id: 9)
Tag.create(body_part: "upper_body", exercise_id: 10)
Tag.create(body_part: "upper_body", exercise_id: 11)
Tag.create(body_part: "upper_body", exercise_id: 36)
Tag.create(body_part: "upper_body", exercise_id: 28)
Tag.create(body_part: "upper_body", exercise_id: 31)

Tag.create(body_part: "lower_body", exercise_id: 12)
Tag.create(body_part: "lower_body", exercise_id: 13)
Tag.create(body_part: "lower_body", exercise_id: 14)
Tag.create(body_part: "lower_body", exercise_id: 15)
Tag.create(body_part: "lower_body", exercise_id: 16)
Tag.create(body_part: "lower_body", exercise_id: 17)
Tag.create(body_part: "lower_body", exercise_id: 18)
Tag.create(body_part: "lower_body", exercise_id: 19)
Tag.create(body_part: "lower_body", exercise_id: 20)
Tag.create(body_part: "lower_body", exercise_id: 21)
Tag.create(body_part: "lower_body", exercise_id: 22)
Tag.create(body_part: "lower_body", exercise_id: 23)

Tag.create(body_part: "core", exercise_id: 1)
Tag.create(body_part: "core", exercise_id: 4)
Tag.create(body_part: "core", exercise_id: 5)
Tag.create(body_part: "core", exercise_id: 6)
Tag.create(body_part: "core", exercise_id: 7)
Tag.create(body_part: "core", exercise_id: 9)
Tag.create(body_part: "core", exercise_id: 12)
Tag.create(body_part: "core", exercise_id: 19)
Tag.create(body_part: "core", exercise_id: 21)
Tag.create(body_part: "core", exercise_id: 22)
Tag.create(body_part: "core", exercise_id: 23)
Tag.create(body_part: "core", exercise_id: 24)
Tag.create(body_part: "core", exercise_id: 25)
Tag.create(body_part: "core", exercise_id: 26)
Tag.create(body_part: "core", exercise_id: 27)
Tag.create(body_part: "core", exercise_id: 28)
Tag.create(body_part: "core", exercise_id: 29)
Tag.create(body_part: "core", exercise_id: 30)
Tag.create(body_part: "core", exercise_id: 31)
Tag.create(body_part: "core", exercise_id: 32)
Tag.create(body_part: "core", exercise_id: 33)
Tag.create(body_part: "core", exercise_id: 34)
Tag.create(body_part: "core", exercise_id: 35)

Quote.create(quotation: "SORE TODAY. STRONG TOMORROW.")
Quote.create(quotation: "NO PAIN NO GAIN")
Quote.create(quotation: "THE ONLY BAD WORKOUT IS THE ONE YOU DIDN’T DO.")
Quote.create(quotation: "GOOD THINGS COME TO THOSE WHO SWEAT")
Quote.create(quotation: "NO MATTER HOW SLOW YOU GO YOU ARE STILL LAPPING EVERYBODY ON THE COUCH")
Quote.create(quotation: "SWEAT IS JUST FAT CRYING")
Quote.create(quotation: "WAKE. WORK. KICK ASS. REPEAT.")
Quote.create(quotation: "WOW I REALLY REGRET THAT WORKOUT -SAID NO ONE EVER")
Quote.create(quotation: "DON’T LIMIT YOUR CHALLENGES. CHALLENGE YOUR LIMITS.")
Quote.create(quotation: "YOU DON’T HAVE TO GO FAST, YOU JUST HAVE TO GO")
Quote.create(quotation: "WAKE UP WITH DETERMINATION, GO TO BED WITH SATISFACTION")
Quote.create(quotation: "IF YOU HAVE A BODY, YOU ARE AN ATHLETE")
Quote.create(quotation: "DON’T WISH FOR IT, WORK FOR IT")
Quote.create(quotation: "JUST KEEP MOVING")
Quote.create(quotation: "YOU CAN DO ANYTHING FOR  A MINUTE")
Quote.create(quotation: "THE DIFFERENCE BETWEEN TRY AND TRIUMPH IS A LITTLE UMPH")
Quote.create(quotation: "WHETHER YOU THINK YOU CAN OR YOU CAN’T, YOU’RE RIGHT")
Quote.create(quotation: "JUST WHEN THE CATERPILLAR THOUGHT THE WORLD WAS ENDING, IT TURNED INTO A BUTTERFLY")
Quote.create(quotation: "DON’T BE AFRAID OF FAILURE. THIS IS THE WAY TO SUCCEED.")
Quote.create(quotation: "SUCCESS IS THE SUM OF SMALL EFFORTS, REPEATED DAY-IN AND DAY-OUT")
Quote.create(quotation: "IF SOMETHING STANDS BETWEEN YOU AND YOUR SUCCESS, MOVE IT. NEVER BE DENIED.")
